program sklearn_mlp_face_hash_debug_1.aleo;

struct Struct0:
    x0 as i64;
    x1 as i64;

struct Struct1:
    x0 as i64;

struct Struct2:
    struct1_0 as Struct0;
    struct1_1 as Struct0;
    struct1_2 as Struct0;
    struct1_3 as Struct0;
    struct1_4 as Struct0;
    struct1_5 as Struct0;
    struct1_6 as Struct0;
    struct1_7 as Struct0;
    struct1_8 as Struct1;
    struct1_9 as Struct1;
    struct1_10 as Struct1;
    struct1_11 as Struct1;
    struct1_12 as Struct1;
    struct1_13 as Struct1;
    struct1_14 as Struct1;
    struct1_15 as Struct1;
    struct1_16 as Struct1;
    struct1_17 as Struct1;
    struct1_18 as Struct1;
    struct1_19 as Struct1;
    struct1_20 as Struct1;
    struct1_21 as Struct1;
    struct1_22 as Struct1;
    struct1_23 as Struct1;
    struct1_24 as Struct1;
    struct1_25 as Struct1;
    struct1_26 as Struct1;
    struct1_27 as Struct1;
    struct1_28 as Struct1;
    struct1_29 as Struct1;
    struct1_30 as Struct1;
    struct1_31 as Struct1;

struct Struct3:
    struct1_0 as Struct0;
    struct1_1 as Struct0;
    struct1_2 as Struct0;
    struct1_3 as Struct0;
    struct1_4 as Struct0;
    struct1_5 as Struct0;
    struct1_6 as Struct0;
    struct1_7 as Struct1;
    struct1_8 as Struct1;
    struct1_9 as Struct1;
    struct1_10 as Struct1;
    struct1_11 as Struct1;
    struct1_12 as Struct1;
    struct1_13 as Struct1;
    struct1_14 as Struct1;
    struct1_15 as Struct1;
    struct1_16 as Struct1;
    struct1_17 as Struct1;
    struct1_18 as Struct1;
    struct1_19 as Struct1;
    struct1_20 as Struct1;
    struct1_21 as Struct1;
    struct1_22 as Struct1;
    struct1_23 as Struct1;
    struct1_24 as Struct1;
    struct1_25 as Struct1;
    struct1_26 as Struct1;
    struct1_27 as Struct1;
    struct1_28 as Struct1;
    struct1_29 as Struct1;
    struct1_30 as Struct1;
    struct1_31 as Struct1;

function main:
    input r0 as Struct2.private;
    input r1 as Struct2.private;
    input r2 as Struct2.private;
    input r3 as Struct2.private;
    input r4 as Struct2.private;
    input r5 as Struct3.private;
    input r6 as Struct3.private;
    input r7 as Struct3.private;
    input r8 as Struct3.private;
    input r9 as Struct3.private;
    input r10 as Struct3.private;
    input r11 as Struct3.private;
    input r12 as Struct3.private;
    input r13 as Struct3.private;
    input r14 as Struct3.private;
    input r15 as Struct3.private;
    output 1i64 as i64.public;
    output 2i64 as i64.public;
    output 0field as field.public;
